version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Soi07052003@
      MYSQL_DATABASE: hrm
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: hrm-app
    ports:
      - "8989:8989"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrm?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/hrm?useSSL=false&allowPublicKeyRetrieval=true

volumes:
  mysql_data: